module_order:
        - SAV:
                - exclude_fn:
                        './reads/'
                - exclude_fn:
                        './bams/'
        - DRAGEN:
                - exclude_fn:
                        './hot/'
        - bclconvert:
                - exclude_fn:
                        './hot/'

exclude_modules:
- snippy
